<a href="https://colab.research.google.com/github/Rashijain07/INTERNSAVY_Task1/blob/main/Graduate_Admissions_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Accessing dataset from local directory

In [2]:
from google.colab import files
uploaded=files.upload()

Saving Admission_Predict.csv to Admission_Predict.csv


Load dataset

In [4]:
dataset=pd.read_csv("Admission_Predict.csv")
dataset

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
395         396        324          110                  3  3.5   3.5  9.04   
396         397        325          107                  3  3.0   3.5  9.11   
397         398        330          116                  4  5.0   4.5  9.45   
398         399        312          103                  3  3.5   4.0  8.78   
399         400        333          117                  4  5.0   4.0  9.66   

     Research  Chance of Admit   
0           1              0.92  
1           1              0.76  
2           1              0.72  
3           1              0.80  
4           0              0.65  
..        ...               ...  
395         1              0.82  
396         1              0.84  
397         1              0.91  
398         0              0.67  
399         1              0.95  

[400 rows x 9 columns]

Summarize dataset

In [5]:
print(dataset.head())
print(dataset.shape)

   Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65  
(400, 9)


Segregate dataset into X & Y

In [6]:
X=dataset.iloc[:,:-1].values
X

array([[  1.  , 337.  , 118.  , ...,   4.5 ,   9.65,   1.  ],
       [  2.  , 324.  , 107.  , ...,   4.5 ,   8.87,   1.  ],
       [  3.  , 316.  , 104.  , ...,   3.5 ,   8.  ,   1.  ],
       ...,
       [398.  , 330.  , 116.  , ...,   4.5 ,   9.45,   1.  ],
       [399.  , 312.  , 103.  , ...,   4.  ,   8.78,   0.  ],
       [400.  , 333.  , 117.  , ...,   4.  ,   9.66,   1.  ]])

In [7]:
Y=dataset.iloc[:,-1].values
Y

array([0.92, 0.76, 0.72, 0.8 , 0.65, 0.9 , 0.75, 0.68, 0.5 , 0.45, 0.52,
       0.84, 0.78, 0.62, 0.61, 0.54, 0.66, 0.65, 0.63, 0.62, 0.64, 0.7 ,
       0.94, 0.95, 0.97, 0.94, 0.76, 0.44, 0.46, 0.54, 0.65, 0.74, 0.91,
       0.9 , 0.94, 0.88, 0.64, 0.58, 0.52, 0.48, 0.46, 0.49, 0.53, 0.87,
       0.91, 0.88, 0.86, 0.89, 0.82, 0.78, 0.76, 0.56, 0.78, 0.72, 0.7 ,
       0.64, 0.64, 0.46, 0.36, 0.42, 0.48, 0.47, 0.54, 0.56, 0.52, 0.55,
       0.61, 0.57, 0.68, 0.78, 0.94, 0.96, 0.93, 0.84, 0.74, 0.72, 0.74,
       0.64, 0.44, 0.46, 0.5 , 0.96, 0.92, 0.92, 0.94, 0.76, 0.72, 0.66,
       0.64, 0.74, 0.64, 0.38, 0.34, 0.44, 0.36, 0.42, 0.48, 0.86, 0.9 ,
       0.79, 0.71, 0.64, 0.62, 0.57, 0.74, 0.69, 0.87, 0.91, 0.93, 0.68,
       0.61, 0.69, 0.62, 0.72, 0.59, 0.66, 0.56, 0.45, 0.47, 0.71, 0.94,
       0.94, 0.57, 0.61, 0.57, 0.64, 0.85, 0.78, 0.84, 0.92, 0.96, 0.77,
       0.71, 0.79, 0.89, 0.82, 0.76, 0.71, 0.8 , 0.78, 0.84, 0.9 , 0.92,
       0.97, 0.8 , 0.81, 0.75, 0.83, 0.96, 0.79, 0.

  Converting Y values into 0 and 1

In [9]:
import numpy as np

def convert_to_binary(data, threshold):
    binary_data = np.where(data < threshold, 0, 1)
    return binary_data


values = np.array(Y)
threshold = 0.5

binary_values = convert_to_binary(values, threshold)
print(binary_values)


[1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1
 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 0 0 0 0 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1]


In [10]:
Y=binary_values.reshape(len(Y),1)
Y

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
    

Splitting dataset into train & test

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,Y, test_size=0.25, random_state=0)
print(X_train)
print(X_test)

[[251.   320.   104.   ...   2.5    8.57   1.  ]
 [ 64.   315.   107.   ...   3.     8.5    1.  ]
 [313.   311.   107.   ...   4.5    9.     1.  ]
 ...
 [118.   290.   104.   ...   2.5    7.46   0.  ]
 [ 48.   339.   119.   ...   4.     9.7    0.  ]
 [173.   322.   110.   ...   5.     9.13   1.  ]]
[[133.   309.   105.     5.     3.5    3.5    8.56   0.  ]
 [310.   308.   110.     4.     3.5    3.     8.6    0.  ]
 [342.   326.   110.     3.     3.5    3.5    8.76   1.  ]
 [197.   306.   105.     2.     3.     2.5    8.26   0.  ]
 [247.   316.   105.     3.     3.     3.5    8.73   0.  ]
 [ 61.   309.   100.     2.     3.     3.     8.1    0.  ]
 [156.   312.   109.     3.     3.     3.     8.69   0.  ]
 [262.   312.   104.     3.     3.5    4.     8.09   0.  ]
 [142.   332.   118.     2.     4.5    3.5    9.36   1.  ]
 [215.   331.   117.     4.     4.5    5.     9.42   1.  ]
 [ 38.   300.   105.     1.     1.     2.     7.8    0.  ]
 [135.   333.   113.     5.     4.     4.     9.28 

Feature Scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)
X_train
X_test


array([[-0.61932605, -0.64835121, -0.39111906,  1.61356406,  0.05765323,
         0.00734738, -0.08655068, -1.12815215],
       [ 0.93793378, -0.73299236,  0.41697817,  0.75831809,  0.05765323,
        -0.54370626, -0.02102335, -1.12815215],
       [ 1.21947228,  0.79054835,  0.41697817, -0.09692788,  0.05765323,
         0.00734738,  0.24108596,  0.88640526],
       [-0.05624905, -0.90227466, -0.39111906, -0.95217384, -0.42279036,
        -1.0947599 , -0.57800564, -1.12815215],
       [ 0.38365486, -0.05586316, -0.39111906, -0.09692788, -0.42279036,
         0.00734738,  0.19194046, -1.12815215],
       [-1.25278767, -0.64835121, -1.19921629, -0.95217384, -0.42279036,
        -0.54370626, -0.84011495, -1.12815215],
       [-0.41697025, -0.39442776,  0.25535873, -0.09692788, -0.42279036,
        -0.54370626,  0.12641314, -1.12815215],
       [ 0.51562603, -0.39442776, -0.55273851, -0.09692788,  0.05765323,
         0.55840102, -0.85649678, -1.12815215],
       [-0.54014334,  1.29839525

Training

In [14]:
import warnings
warnings.simplefilter("ignore")

from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

Prediction

In [16]:
input=[[1, 223, 175, 3, 13, 45, 10, 1]]
result= model.predict(sc.transform(input))
print(result)
if(result==1):
  print("Chance of taking admission is high")
else:
  print("Chance of taking admission is low")

[1]
Chance of taking admission is high


Evaluation

In [17]:
y_pred=model.predict(X_test)

In [18]:
from sklearn.metrics import accuracy_score
print("Accuracy score is : {0}% ".format(accuracy_score(y_pred, y_test)*100))

Accuracy score is : 94.0% 
